// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVvQ4Tl7zO_tVjM1ox65Bnsr7Ar9kEut8',
    appId: '1:827456032715:android:1caca69e82ac49c4e9704e',
    messagingSenderId: '827456032715',
    projectId: 'flutter-chatapp-5ae7b',
    storageBucket: 'flutter-chatapp-5ae7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvk-QLSGc_8-AnC7GFL7xkLm-ed711Fqc',
    appId: '1:827456032715:ios:d5e2373bb704d171e9704e',
    messagingSenderId: '827456032715',
    projectId: 'flutter-chatapp-5ae7b',
    storageBucket: 'flutter-chatapp-5ae7b.appspot.com',
    iosClientId: '827456032715-vl5ol8kaag598ieov61hflpqducgmjgm.apps.googleusercontent.com',
    iosBundleId: 'com.jonghun.flutterchatapp',
  );
}
